default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: howarts_rails_development
  username: postgres
  password: valesca
  port: 5432

test:
  <<: *default
  database: howarts_rails_test
  username: postgres
  password: valesca
  host: localhost
  port: 5432

production:
  <<: *default
  database: howarts_rails_production
  username: howarts_rails
  password: <%= ENV["HOWARTS_RAILS_DATABASE_PASSWORD"] %>
